name: eg-cfg-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.9.19
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - asttokens==2.4.1
      - black==24.8.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.7
      - columnize==0.3.11
      - decompyle3==3.9.2
      - decorator==5.1.1
      - dis==1.0.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - filelock==3.18.0
      - fsspec==2025.5.0
      - huggingface-hub==0.31.4
      - idna==3.10
      - ipdb==0.13.13
      - ipython==8.18.1
      - jedi==0.19.1
      - joblib==1.5.0
      - matplotlib-inline==0.1.7
      - mypy-extensions==1.0.0
      - nose==1.3.7
      - numpy==2.0.2
      - packaging==24.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.48
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyficache==2.3.1
      - pygments==2.18.0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.16.0
      - spark-parser==1.8.9
      - stack-data==0.6.3
      - term-background==1.0.1
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - tomli==2.0.1
      - tqdm==4.67.1
      - tracer==0.3.2
      - traitlets==5.14.3
      - transformers==4.49.0
      - trepan3k==1.2.11
      - trepanxpy==1.1.1
      - typing-extensions==4.12.2
      - uncompyle6==3.9.2
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - x-python==1.5.1
      - xdis==6.1.1
      - xmlformatter==0.2.6
